#!/bin/bash

VPX_PATH="/Users/jmillard/vpinball/build"
TABLES_PATH="/Users/jmillard/tables"

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

while :; do
   games=($VPX_PATH/res/exampleTable.vpx)

   for file in `ls ${TABLES_PATH}/*.vpx | sort --ignore-case`
   do
      games=(${games[*]} "$file")
   done

   printf "usage: vpx [-fullscreen] [-extractvbs] [-pov] [-povedit]\n\nTables:\n\n"
   printf "\nTables:\n\n"

   for index in "${!games[@]}"; do
      printf "%s\t%s\n" "$index" "${games[$index]}"
   done

   printf "\nTable number (Q to quit)? "
   read game_no

   if [[ "$game_no" != "Q" ]] && [ "$game_no" != "q" ]; then
      if [[ "$*" == *"-extractvbs"* ]]; then
         ${VPX_PATH}/VPinballX_GL -extractvbs "${games[$game_no]}"
      elif [[ "$*" == *"-povedit"* ]]; then
         ${VPX_PATH}/VPinballX_GL -povedit "${games[$game_no]}"
      elif [[ "$*" == *"-pov"* ]]; then
         ${VPX_PATH}/VPinballX_GL -pov "${games[$game_no]}"
      elif [[ "$*" == *"-fullscreen"* ]]; then
         ${VPX_PATH}/VPinballX_GL -play "${games[$game_no]}"
      else
         ${VPX_PATH}/VPinballX_GL -DisableTrueFullscreen -play "${games[$game_no]}"
      fi
   else
      exit
   fi
done

IFS=$SAVEIFS
