#!/bin/bash

WINESRC="/Users/jmillard/wine-latest/wine"

cd ../inc/wine

for i in $(find .); do 
  if [ "$i" != "./dlls/vbscript/parser.tab.c" ] &&
     [ "$i" != "./dlls/vbscript/parser.tab.h" ]; then
     if [ ! -d "$i" ]; then
        if [ -f "$WINESRC/$i" ]; then
            DIFF=$(diff "$i" "$WINESRC/$i")
	    if [ "$DIFF" != "" ]; then
	       echo "------------------------------------"
	       echo ""
	       echo "diff \"$i\" \"$WINESRC/$i\""
	       echo ""
	       diff "$i" "$WINESRC/$i"
               echo ""
	    fi
        fi
     fi
  fi
done

